// REDUX CONSTANTS
const constants = {
  CREATE_USER: 'CREATE_USER',
  USER_AUTH: 'USER_AUTH',
  USER: 'USER_INFO',
  EDIT_PROFILE: 'EDIT_PROFILE',
  ADD_PROFILE_PIC: 'ADD_PROFILE_PIC',
  SEARCH_CAMPAIGNS: 'SEARCH_CAMPAIGNS',
  FILTER_CAMPAIGNS: 'FILTER_CAMPAIGNS',
  ERROR: 'ERROR',
  MESSAGE: 'MESSAGE',
};

export default constants;
